language: python
python:
  - "2.7"
env: DJANGO_SETTINGS_MODULE="YASN.settings"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python manage.py test posts.models
  - coverage run --source=posts.models manage.py test posts.models
after_success: coveralls
