language: python
python:
  - "2.7"
env: DJANGO_SETTINGS_MODULE="YASN.settings"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - python manage.py test posts
  - coverage run --source=posts manage.py test posts
after_success: coveralls
