language: python
python:
  - "2.6"
  - "2.7"
env: DJANGO_SETTINGS_MODULE="YASN.settings"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  coverage run --source=posts.models manage.py test
after_success:
  coveralls
